ImperialCollegeLondon/sharpy

sharpy/utils/h5utils.py
Remove the following warning:
H5pyDeprecationWarning: dataset.value has been deprecated. Use dataset[()] instead.  "Use dataset[()] instead.", H5pyDeprecationWarning)
=> Remove H5pyDeprecationWarning

sharpy/aero/models/aerogrid.py, sharpy/solvers/aerogridloader.py, sharpy/utils/settings.py
Fixes the `DynamicControlSurface` interface with `Aerogrid` via `AerogridLoader`. A setting was missing to parse the settings of the control surface.
I have also updated `settings.py` to include `list(dict)` as a possible setting type.
Finally, the settings in `AerogridLoader` have been updated to autogenerate the settings table.
=> Fix dynamic control surface and settings for aerogridloader

docs/source/content/installation.md
As part of the review for https://github.com/openjournals/joss-reviews/issues/1885.
I am running the docker image in Windows, and needed to change the order of this argument to avoid getting an error from bash: `/bin/bash: --name: invalid option`.
=> Change position of --name argument in docs

docs/source/content/casefiles.rst, docs/source/content/solvers.rst, docs/source/includes/solvers/loader/PreSharpy.rst, docs/source/includes/solvers/loader_solvers.rst, sharpy/generators/gustvelocityfield.py, sharpy/linear/assembler/linearaeroelastic.py, sharpy/presharpy/presharpy.py, sharpy/utils/docutils.py, sharpy/utils/settings.py, sharpy/utils/solver_interface.py
Following on from the discussion in #32, default settings now get the value specified in their respective `settings_types` as opposed to having their own type.
For an unprovided setting with `settings_type['current_setting'] = list(float)` and `settings_default['current_setting'] = [1. , 0., 0.]`
Old behaviour would process setting as `list`. New behaviour will process it as `np.array` (as are all user-defined settings that are given the type `list(float)`).
Fixes #33 as well, no need for the revert.
All tests passed :+1:
=> Default settings get type specified for the setting rather than their own type

docs/source/includes/utils/settings/check_settings.rst, docs/source/includes/utils/settings/index.rst, sharpy/generators/gustvelocityfield.py, sharpy/linear/assembler/linearbeam.py, sharpy/linear/assembler/linearuvlm.py, sharpy/presharpy/presharpy.py, sharpy/rom/balanced.py, sharpy/solvers/stepuvlm.py, sharpy/utils/exceptions.py, sharpy/utils/settings.py
Introduces a small new feature to check that settings are valid and also adds valid options to the relevant settings' documentation.
The same way we have `settings_types`, `settings_default` etc, we now have the dictionary `settings_options` for those settings that are either `int`, `str` or `list(str)` that have certain possible options. The entry for each setting in `settings_options` is a `list`.
Example: 
The convection scheme in `StepUvlm` is an `int` that can be `0`, `2` or `3`. The new dictionary would have an entry like:
```settings_options['convection_scheme'] = [0, 2, 3]```
To implement this feature to your code:
* Documentation table: 
```   __doc__ += settings_table.generate(settings_types, settings_default, settings_description, settings_options)```
* Settings to custom …
=> New settings check against valid options

tests/coupled/multibody/double_pendulum/test_double_pendulum_geradin.py, tests/coupled/multibody/fix_node_velocity_wrtA/test_fix_node_velocity_wrtA.py, tests/coupled/prescribed/gamma_dot_test/test_gamma_dot.py, tests/xbeam/test_xbeam.py
Some unittests were incorrectly calling `tearDowns()` instead of `tearDown()`. This pull request fixes this.
=> Fix typo in unittests using tearDowns instead of tearDown

docs/source/content/installation.md, docs/source/includes/rom/frequencyresponseplot/FrequencyResponseComparison.rst, docs/source/includes/rom/frequencyresponseplot/index.rst, docs/source/includes/rom/index.rst, docs/source/includes/utils/exceptions/NotValidSetting.rst, docs/source/includes/utils/exceptions/index.rst
Included explicit instructions to install the release and development builds from source.
I haven't made any particular references to `xbeam` or `UVLM` releases, only a checkout from master is required. If you are happy we leave it as is.
The other option would be to have release tags in those repos and include them in the instructions, as is done with SHARPy.
=> Updated installation instructions

Dockerfile, docs/JOSS/paper.bib, docs/JOSS/paper.md
Fixes minor typos in JOSS paper, namely:
- Changed `much` to `more` in par.4
- Fixed capitalisation in the bibliography
=> JOSS Paper Minor typos fixed

sharpy/postproc/saveparametriccase.py
This is a very simple post-processor that appends to the output data a config file containing any user defined parameter names and values associated to that simulation.
This is useful when running SHARPy in batch and changing the name of the simulation to include the parameter value is no longer sufficient/comfortable.
The input to this postproc is done through its settings files where the `parameters` setting takes any dictionary of user-desired `'<parameter_name>': <parameter_value>` entries.
=> Simple post-processor to save simulation parameters for batch runs

sharpy/generators/gridbox.py
- Removed all ".value" in Gridbox class
- Raised error since coordinates and spacings are not stored in dict format
=> [fix] Fixed bug in Gridbox class

sharpy/postproc/savedata.py, sharpy/rom/krylov.py, sharpy/utils/rom_interface.py, tests/linear/goland_wing/test_goland_flutter.py, tests/linear/rom/test_krylov.py
Small enhancement to `SaveData` postproc that adds a `save_rom` setting that saves the ROM state space as well as the reduced order bases used for reduction.
=> Support to save ROM projector matrices

.github/workflows/sharpy_tests.yaml, sharpy/aero/utils/mapping.py, sharpy/postproc/aeroforcescalculator.py
Fixes bug in `AeroforcesCalculator`, where the total moments at the A frame reference location did not include the contribution from the nodal forces, it just summed over the nodal moments.
=> Fix bug in computing total moments in A frame

docs/source/content/installation.md
Added missing directory change after building the repo, to go back one level up from the `build` folder before being able to load the environment variables.
=> Update installation docs

sharpy/solvers/_basestructural.py, sharpy/structure/utils/xbeamlib.py
The absolute tolerance used in xbeam for the convergence test is added as a user-defined input to the base structural solver and is passed to xbeam with xbopts. The main reason for the change is a bug in xbeam where the absolute tolerance was defined as too small to be able to catch significant small residuals in convergence tests for which the relative tolerance fails (see https://github.com/ImperialCollegeLondon/xbeam/pull/11). As a result, the structural solver did not converge for the external gust assembler test part of SHARPy's unittest. Further, it has been noticed that the absolute tolerance was defined differently in various functions.
Hence, this pull request includes the following changes:
- define the absolute tolerance for convergence checks within xbeam as a central …
=> Handle absolute tolerance for structural convergence tests as input settings and increase default value

docs/source/content/example_notebooks/UDP_control/tutorial_udp_control.ipynb, sharpy/aero/utils/utils.py, sharpy/postproc/savedata.py
Hey team,
I stumbled across two minor bugs recently that are fixed in this pull request.
The first bug occurs when linearization is performed, but StaticTrim is the only solver used in the SHARPy simulation flow. The reason for this is that the aero solver settings (needed to find the velocity generator settings) cannot be retrieved, because StaticTrim was not previously included as one of the possible solvers. This is now changed.
The second bug causes an error when a linear system is saved but an old file already exists. This file cannot be overwritten, so the old file is now removed (as it was previously already for the nonlinear output file).  I could also remove the workaround for this bug from the UDP tutorial. 
The changes are quite minor and should not take long to review. I have …
=> Minor bug fixes in aero util functions and save data postprocessor

sharpy/utils/generate_cases.py
hotfix - requesting to merge to both main and develop.
issue with using overload of + operator - if polars of the same length, the result would be a summed array rather than concatenation
=> fix polars concatenation in assembly of aeroinformation - main

Dockerfile
The docker still uses the outdated minimal conda environment. This causes an error since it still uses Python 3.7 instead of 3.10.
=> Update docker environment 

.readthedocs.yaml, docs/requirements_rtd
necessitated by readthedocs updating the build process
https://docs.readthedocs.io/en/stable/config-file/v2.html#migrating-from-the-web-interface
=> Hotfix for documentation - main

.readthedocs.yaml, docs/requirements_rtd
necessitated by readthedocs updating the build process
https://docs.readthedocs.io/en/stable/config-file/v2.html#migrating-from-the-web-interface
=> Hotfix for documentation - develop

docs/source/content/installation.md, docs/source/includes/linear/src/lingebm/newmark_ss.rst, sharpy/linear/src/lingebm.py, tests/linear/rom/test_springmasssystem.py
I spotted some small errors in the documentation of the `newmark_ss` function (the code was ok!) and I decided to improve them since this is a pretty good tutorial on the method that may be useful for my team as well. Therefore I did some improvements such as
- Correcting mistakes such as missed parenthesis; extra derivative dots; etc.
- Making the notation more uniform: C was used for both the damping matrix and the state-space C matrix; q and x were used for the position interchangeably; now all matrices are bold upper-case and vectors are bold lower-case.
I tried to make the code slightly faster and more accurate by reusing the factorization of the Ass1 matrix and by using the factorization of the M matrix to compute the multiplication by the inverse (due to the triangular structure of …
=> Improve docs and code of newmark_ss

Dockerfile
Updated XBeam to change compile flags used in GFortran. The `-ftree-parallelize-loops=4` optimisation flag was found to make the beam solver take considerably longer to run than without it. The `-ofast` flag was added as this should increase performance in some cases with no noticeable impact on results.
=> Update XBeam version to include compiler optimisation

docs/source/content/example_notebooks/UDP_control/tutorial_udp_control.ipynb, sharpy/generators/gustvelocityfield.py, sharpy/postproc/aeroforcescalculator.py, sharpy/postproc/savedata.py, sharpy/structure/utils/modalutils.py
Hey,
Here are just a few minor bug fixes:
1. Fixed the headers and output shapes of the force and moment matrix that are written to a file in the postprocessor aeroforcescalculator.py ( #208).
2. There was a small bug in modalutils.py that caused not exporting 10 of the last mode shapes if rigid body motions are considered ( #208).
3. There's a small format bug that does not cause the Jupyter Notebook for the UDP control tutorial to open (at least for my visual code) and it's also not displayed in the documents (might the caused by the same format error).
4. Most importantly, I deleted some left-over debugging prints giving Ben headaches, although he hopefully uses the remove button himself next time (better than taking paracetamole).
5.  In one previous merge request, the indentation in …
=> A few minor bug fixes

sharpy/linear/src/lingebm.py
Rendering of the page is attached for convenience
[newmark_ss — SHARPy 2.2 documentation.pdf](https://github.com/ImperialCollegeLondon/sharpy/files/14451862/newmark_ss.SHARPy.2.2.documentation.pdf)
=> Correct typos caught by Divya Sanghi

Dockerfile
Removed some unnecessary flags used when installing Mamba, causing it to fail. Ideally Mamba would be removed as the new pip install method does not require it, however CMAKE cannot find BLAS this way - tried a few install methods. This shouldn't cause any issues as long as the old environment in /utils/ remains.
=> Fix Github Runner Docker build failing

docs/source/content/installation.md
Some users have had an issue with Conda failing whilst creating the environment, giving the following message:
```bash
Collecting package metadata (repodata.json): - Killed
```
This is due to Conda running out of RAM during install, documented [here](https://stackoverflow.com/questions/74566580/why-is-conda-create-env-killed). This is in line with problems found a few months ago, with 8 GB of RAM often not being sufficient. Unfortunately Conda isn't very efficient with memory, and there is little we can do about this. 
I have updated the docs to include 3 options to fix this issue:
* Increase available RAM (if running on a compute cluster etc)
* Use [Mamba](https://mamba.readthedocs.io/en/latest/), a more efficient drop-in replacement for Conda. This is what I personally use locally and …
=> Updated docs to address issue with conda install failing

setup.py
NumPy 2.0 has been released, which depreciates many functions that have been used in SHARPy. This now causes many unit tests to fail, and there is also a corresponding SciPy version which presents issues. This is a temporary fix which sets an upper ceiling on the versions which can be used (was previously set to use latest), however aim to update the code in due course.
=> Temporary Fix for NumPy 2.0 Issues (Main Branch)

sharpy/postproc/aeroforcescalculator.py, sharpy/utils/datastructures.py, tests/uvlm/static/polars/test_polars.py
This post-processor was previously giving erroneous results as the input forces were not in the expected (inertial) frame of reference, instead being in the flow direction relative to the body frame.
I did code up a more elegant post-processor, but it failed unit tests because of how the airfoil polars are implemented, and so I reverted to a modified version of the original. I really do not like this approach, as the forces used need to be mapped from B -> A -> G FoR, even though the UVLM forcing naturally should occur in the G FoR, however fixing this properly is not a trivial task and would require a rewrite of the polar code. This is something that should be investigated for anyone working with airfoil polars, as many of the aerodynamic forcing values within the solvers do not have the …
=> Fix AeroForcesCalculator giving forces in wrong frame of reference

sharpy/utils/generate_cases.py
not caught since nobody was using this - but will become a dependency of the statictrimMB solver so am getting this done now. thanks!
=> Bug fix for generate_full_structure

sharpy/postproc/aerogridplot.py
silly mistake really - position in Gframe of multibody is offset by cga_0 not cga(t)
=> Update body and wake FoR multiplication
