- docs/source/conf.py
- docs/source/content/installation.md
- docs/source/includes/aero/index.rst
- docs/source/includes/aero/models/index.rst
- docs/source/includes/controllers/index.rst
- docs/source/includes/index.rst
- docs/source/includes/rom/index.rst
- docs/source/includes/structure/index.rst
- docs/source/includes/structure/models/index.rst
- docs/source/includes/structure/utils/index.rst
- docs/source/includes/utils/index.rst
- sharpy/solvers/statictrim.py
- sharpy/utils/docutils.py
- tests/docs/test_docs.py
A couple updates to docs and clean up
> Documentation fixes/updates

- sharpy/solvers/modal.py
- sharpy/structure/utils/modalutils.py
Modal matrices can now be calculated with a given time step solution calculated previously.
Names of modal output files now reflect this new possibility and are accordingly updated
> Improved modal solver

- docs/JOSS/paper.bib
- docs/JOSS/paper.md
This PR aims to solve #36. @rafapalacios can you have a look at the paragraph and approve/give feedback before I merge?
> Added information about competing software in JOSS paper

- README.md
Guys, the capabilities section only makes reference to the nonlinear part of the code, and for aircraft.
Any chance we can put together a few more lines about your part of the code? I feel like it is mature enough, and already available through master.
> Small typo in README.md and updates to it

- sharpy/sharpy_main.py
- sharpy/utils/exceptions.py
- sharpy/utils/input_arg.py
- sharpy/utils/solver_interface.py
An `error.log` file is created whenever an exception is found whilst running SHARPy.
In addition, exceptions have been added for:
- Solver in `flow` not in `dict_of_solvers`
- Solver settings not found in `.sharpy`
> Error log file created when program encounters exceptions

- .gitmodules
- docs/source/conf.py
- sharpy/aero/utils/uvlmlib.py
- sharpy/linear/assembler/linearuvlm.py
- sharpy/linear/src/assembly.py
- sharpy/linear/src/lib_dbiot.py
- sharpy/linear/src/lin_aeroelastic.py
- sharpy/linear/src/linuvlm.py
- sharpy/linear/src/multisurfaces.py
- sharpy/linear/src/surface.py
- sharpy/linear/src/uvlmutils.py
- sharpy/postproc/aerogridplot.py
- sharpy/postproc/plotflowfield.py
- sharpy/solvers/dynamiccoupled.py
- sharpy/solvers/prescribeduvlm.py
- sharpy/solvers/shwuvlm.py
- sharpy/solvers/staticcoupled.py
- sharpy/solvers/staticuvlm.py
- sharpy/solvers/steplinearuvlm.py
- sharpy/solvers/stepuvlm.py
- sharpy/utils/constants.py
- sharpy/utils/correct_forces.py
- tests/coupled/static/pazy/generate_pazy.py
- tests/coupled/static/test_pazy_static.py
- tests/linear/assembly/test_assembly.py
- tests/linear/derivatives/test_ders.py
- tests/linear/uvlm/test_infinite_span.py
The vortex radius is the distance below which vortex inductions are not computed to avoid the singularity of the vortex field at the vortex position. Before it was hard coded in the aerodynamic library, but this pull request implements the vortex radius of UVLM as input parameter. Specifically, it is defined as an input of the aerodynamic solvers. 
It affects both the linear and the nonlinear aerodynamics.
> Vortex radius as input parameter

- sharpy/io/inout_variables.py
- sharpy/postproc/udpout.py
Very minor addition.
Allows for the UDPout postproc to be used in `offline` mode, i.e. you can now load a pickle and run the output post-processor on all time steps.
> Add support for offline use of UDPout postproc

- docs/source/includes/structure/utils/lagrangeconstraints/BaseLagrangeConstraint.rst
- docs/source/includes/structure/utils/lagrangeconstraints/SampleLagrange.rst
- docs/source/includes/structure/utils/lagrangeconstraints/def_rot_axis_FoR_wrt_node.rst
- docs/source/includes/structure/utils/lagrangeconstraints/def_rot_vel_FoR_wrt_node.rst
- docs/source/includes/structure/utils/lagrangeconstraints/equal_lin_vel_node_FoR.rst
- docs/source/includes/structure/utils/lagrangeconstraints/index.rst
- docs/source/includes/structure/utils/lagrangeconstraints/initialise_lc.rst
- docs/source/includes/structure/utils/lagrangeconstraints/lagrangeconstraint.rst
- docs/source/includes/structure/utils/lagrangeconstraints/lc_from_string.rst
- docs/source/includes/structure/utils/lagrangeconstraints/postprocess.rst
- docs/source/includes/structure/utils/lagrangeconstraints/print_available_lc.rst
- docs/source/includes/structure/utils/lagrangeconstraints/remove_constraint.rst
- docs/source/includes/utils/multibody/disp2state.rst
- docs/source/includes/utils/multibody/disp_and_accel2state.rst
- docs/source/includes/utils/multibody/get_elems_nodes_list.rst
- docs/source/includes/utils/multibody/index.rst
- docs/source/includes/utils/multibody/state2disp.rst
- docs/source/includes/utils/multibody/state2disp_and_accel.rst
- sharpy/postproc/writevariablestime.py
- sharpy/solvers/dynamiccoupled.py
- sharpy/solvers/nonlineardynamicmultibody.py
- sharpy/solvers/nonlinearstaticmultibody.py
- sharpy/structure/models/beam.py
- sharpy/structure/utils/lagrangeconstraints.py
- sharpy/utils/datastructures.py
- sharpy/utils/multibody.py
- Uploaded documentation for the datastructures.py file with the main objective of defining the variables and clarify which FoR they refer to.
- Upload old and include missing multibody documentation.
> Updated docs for DataStructures and Multibody

- tests/linear/assembly/test_assembly.py
Fixes #105 and issue number 6 in UVLM
It requires recompiling UVLM
> Fix accuracy problem in UVLMLin

- docs/source/content/casefiles.rst
- docs/source/content/publications.md
- docs/source/includes/aero/utils/airfoilpolars/Polar.rst
- docs/source/includes/aero/utils/airfoilpolars/index.rst
- docs/source/includes/aero/utils/index.rst
- docs/source/includes/aero/utils/mapping/aero2struct_total_force_mapping.rst
- docs/source/includes/aero/utils/mapping/index.rst
- docs/source/includes/postprocs/Cleanup.rst
- docs/source/includes/postprocs/LiftDistribution.rst
- docs/source/includes/utils/algebra/index.rst
- docs/source/includes/utils/algebra/panel_area.rst
- docs/source/includes/utils/exceptions/NotRecognisedSetting.rst
- docs/source/includes/utils/exceptions/index.rst
- sharpy/generators/straightwake.py
- sharpy/linear/assembler/linearaeroelastic.py
- sharpy/linear/src/linuvlm.py
- sharpy/presharpy/presharpy.py
- sharpy/solvers/aerogridloader.py
Hey guys,
here' is the last pull-request for SHARPy's early summer release. This pull-request updates our submodules XBEAM and UVLM in SHARPy to their latest master branch. 
Have a look and raise any concerns. Thank you!
> Update submodules and conda environments

- .github/workflows/sharpy_tests.yaml
- tests/coupled/dynamic/dynamic_test.py
- tests/coupled/dynamic/hale/generate_hale.py
I added a dynamic unittest to check for errors in SHARPy's dynamic coupled solver. The resulting vertical load and pitching moment at the wing root of the HALE model after some timesteps are compared with reference values produced with SHARPy version 1.3. I have tested the test's functionalities in SHARPy's current "develop" branch and also with a non-functional commit in my fuselage branch. Note that the HALE generation file will be updated as soon as Alvaro's model generation method is pushed and merged.
> Unittest for nonlinear dynamic solver

- sharpy/postproc/asymptoticstability.py
Plots the 0, 45 90 and 135 degree phase of the aeroelastic mode to vtu for visualisation in paraview with the setting `modes_to_plot` in the post-proc `AsymptoticStability`
Currently only plots the flexible degrees of freedom (i.e. for a free-flying aircraft the rigid body contributions are not included). 
Ps. feel free to merge as is or feel free to add the rigid-body contributions... just leaving it here for you to know this is here. @kccwing @sduess you are in charge now! You'll do great :)
> Plot the aeroelastic mode shape to Paraview

- README.md
All cosmetic, just getting the jargon right.
> A bit of clean-up of the readme file of the repo

- docs/source/content/example_notebooks/linear_goland_flutter.ipynb
Minor fixes and a few more comments on the Goland wing flutter example
> Updates to Goland wing example

- docs/source/content/installation.md
Hi,
As a completely new user of SHARPy I faced a few errors while installing the program. I made a few simple mistakes and so have changed a bit of the installation guide to help other newcomers not to make the same mistakes I did. In short, all I've done is change up and add small parts to one or two steps to make it clearer for newer users what to do and what not to, and a rough idea of how long certain steps might take.
Thanks.
> Small additions to the installation guide.

- docs/requirements_rtd
- docs/source/conf.py
https://github.com/readthedocs/sphinx_rtd_theme/pull/1448
https://github.com/readthedocs/sphinx_rtd_theme/issues/1452
readthedocs sphinx_rtd_theme update to 1.2.2 to fix loading of sphinx-contrib-jquery to fix doc search
> Hotfix for documentation search

- sharpy/solvers/noaero.py
NoAero errors out because of missing optional input - fixed
> Update noaero.py for consistency in function input

- utils/environment.yml
Fix for #276 
Include environment.yml scipy version information until rest of package is updated to latest scipy
> Add scipy version info to env yml

- utils/environment.yml
Hotfix as merged on main, duplicate of #277
> Develop: Update environment.yml to fix scipy version issue

- sharpy/postproc/beamplot.py
> Update beamplot.py to have stride option, consistent with aerogridplot.py

- setup.py
Same fix as in https://github.com/ImperialCollegeLondon/sharpy/pull/292
> Temporary Fix for NumPy 2.0 Issues (Develop Branch)

- .github/workflows/sharpy_tests.yaml
- Dockerfile
- setup.py
https://github.com/enthought/mayavi/issues/1289
> Mayavi github dependency restored for hotfix

- sharpy/cases/coupled/X-HALE/generate_xhale.py
As topic - PR for bug fix just so I don't forget to do this.
> Xhale thrust node typo
